import Head from 'next/head'
import Image from 'next/image'
import { Poppins } from 'next/font/google'
import {FiSearch} from 'react-icons/fi'

import styles from '../styles/Home.module.scss'
import backgroundIMg  from '../../public/backgroundImgHome.jpg'
import Input from '@/components/Input'
import Footer from '@/components/Footer'

const poppins = Poppins({
   weight: ['400'], 
   style : ['normal'],
   subsets : ['latin'] // obrigatório
  })

export default function Home() {
  return (
    <>

      <Head>
        <title>Dev Profile</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/devIcon.png"  />
      </Head>


      <main className={`${poppins.className} ${styles.main} `}>

      <Image className={styles.backGroundIMg}  src={backgroundIMg} alt="Imagem de fundo page Home" />

      <div className={styles.inputHome} >
          <Input
        icon={FiSearch}
        placeholder='Pequise pelo nome do usuário'
        isLoading= {true}
        type='text'/>
      </div>
      


      </main>

      <Footer className = {styles.footerHome} />
    </>
  )
}
